package io.hypersistence.utils.hibernate.query;

import java.util.List;
import java.util.Map;

import org.hibernate.engine.spi.SessionFactoryImplementor;
import org.hibernate.engine.spi.SharedSessionContractImplementor;
import org.hibernate.metamodel.mapping.MappingModelExpressible;
import org.hibernate.query.internal.AbstractSqmQuery;
import org.hibernate.query.internal.MutationOrSelectionQueryImpl;
import org.hibernate.query.spi.DomainQueryExecutionContext;
import org.hibernate.query.spi.QueryOptions;
import org.hibernate.query.spi.QueryParameterBindings;
import org.hibernate.query.spi.QueryParameterImplementor;
import org.hibernate.query.sqm.internal.DomainParameterXref;
import org.hibernate.query.sqm.internal.SqmUtil;
import org.hibernate.query.sqm.spi.SqmParameterMappingModelResolutionAccess;
import org.hibernate.query.sqm.sql.spi.SqmTranslation;
import org.hibernate.query.sqm.tree.spi.SqmDmlStatement;
import org.hibernate.query.sqm.tree.spi.SqmStatement;
import org.hibernate.query.sqm.tree.spi.expression.SqmParameter;
import org.hibernate.query.sqm.tree.spi.select.SqmSelectStatement;
import org.hibernate.sql.ast.SqlAstTranslator;
import org.hibernate.sql.ast.tree.MutationStatement;
import org.hibernate.sql.ast.tree.select.SelectStatement;
import org.hibernate.sql.exec.spi.JdbcOperation;
import org.hibernate.sql.exec.spi.JdbcOperationQueryMutation;
import org.hibernate.sql.exec.spi.JdbcParameterBindings;
import org.hibernate.sql.exec.spi.JdbcParametersList;

import io.hypersistence.utils.common.ReflectionUtils;
import jakarta.persistence.Query;

/**
 * The {@link SQLExtractor} allows you to extract the
 * underlying SQL query generated by a JPQL or JPA Criteria API query.
 * <p>
 * For more details about how to use it, check out <a href="https://vladmihalcea.com/get-sql-from-jpql-or-criteria/">this article</a> on <a href="https://vladmihalcea.com/">vladmihalcea.com</a>.
 *
 * @author Vlad Mihalcea
 * @since 2.9.11
 */
public class SQLExtractor {

    protected SQLExtractor() {
    }

    /**
     * Get the underlying SQL generated by the provided JPA query.
     *
     * @param query JPA query
     * @return the underlying SQL generated by the provided JPA query
     */
    public static String from(Query query) {
        if (query instanceof AbstractSqmQuery<?> querySqm) {
            SqmStatement<?> sqmStatement = querySqm.getSqmStatement();

            if (sqmStatement instanceof SqmSelectStatement sqmSelectStatement) {
                return extractSelectSql(querySqm, sqmSelectStatement);
            }
            if (sqmStatement instanceof SqmDmlStatement sqmDmlStatement) {
                return extractMutationSql(querySqm, sqmDmlStatement);
            }
            return querySqm.getQueryString();
        }
        
        // for dml queries created via createQuery
        if(query instanceof MutationOrSelectionQueryImpl oldMutationOrSelectionQuery) {
        	
        	  AbstractSqmQuery<?> querySqm = oldMutationOrSelectionQuery.unwrap(AbstractSqmQuery.class);
        	  SqmStatement<?> sqmStatement = querySqm.getSqmStatement();

              if (sqmStatement instanceof SqmSelectStatement sqmSelectStatement) {
                  return extractSelectSql(querySqm, sqmSelectStatement);
              }
              if (sqmStatement instanceof SqmDmlStatement sqmDmlStatement) {
                  return extractMutationSql(querySqm, sqmDmlStatement);
              }
              return querySqm.getQueryString();
		}
        
        throw new IllegalArgumentException("Unsupported query type: " + (query == null ? "null" : query.getClass().getName()));
    }

    /**
     * Extract SQL from an HQL select statement using the public SQM translation pipeline.
     */
    private static String extractSelectSql(AbstractSqmQuery<?> querySqm, SqmSelectStatement<?> sqmSelect) {
        DomainQueryExecutionContext execCtx = (DomainQueryExecutionContext) querySqm;
        SharedSessionContractImplementor session = execCtx.getSession();
        SessionFactoryImplementor factory = session.getFactory();
        QueryOptions queryOptions = execCtx.getQueryOptions();
        QueryParameterBindings paramBindings = execCtx.getQueryParameterBindings();
        DomainParameterXref domainParameterXref = querySqm.getDomainParameterXref();

        // Step 1: Translate SQM to SQL AST
        SqmTranslation<SelectStatement> sqmInterpretation = factory.getQueryEngine()
            .getSqmTranslatorFactory()
            .createSelectTranslator(
                sqmSelect,
                queryOptions,
                domainParameterXref,
                paramBindings,
                session.getLoadQueryInfluencers(),
                factory.getSqlTranslationEngine(),
                false
            )
            .translate();

        // Step 2: Build JDBC parameter bindings (supports parameterized queries)
        JdbcParameterBindings jdbcParameterBindings = buildJdbcParameterBindings(
            execCtx, domainParameterXref, sqmInterpretation);

        // Step 3: Translate SQL AST to JDBC operation (produces the SQL string)
        SqlAstTranslator<? extends JdbcOperation> translator = factory.getJdbcServices()
            .getJdbcEnvironment()
            .getSqlAstTranslatorFactory()
            .buildSelectTranslator(factory, sqmInterpretation.getSqlAst());

        JdbcOperation jdbcSelect = translator.translate(jdbcParameterBindings, queryOptions);
        return jdbcSelect.getSqlString();
    }

    /**
     * Extract SQL from an HQL update/delete statement using the public SQM translation pipeline.
     */
    private static String extractMutationSql(AbstractSqmQuery<?> querySqm, SqmDmlStatement<?> sqmDml) {
        DomainQueryExecutionContext execCtx = (DomainQueryExecutionContext) querySqm;
        SharedSessionContractImplementor session = execCtx.getSession();
        SessionFactoryImplementor factory = session.getFactory();
        QueryOptions queryOptions = execCtx.getQueryOptions();
        QueryParameterBindings paramBindings = execCtx.getQueryParameterBindings();
        DomainParameterXref domainParameterXref = querySqm.getDomainParameterXref();

        // Step 1: Translate SQM to SQL AST
        SqmTranslation<? extends MutationStatement> sqmInterpretation = factory.getQueryEngine()
            .getSqmTranslatorFactory()
            .createMutationTranslator(
                sqmDml,
                queryOptions,
                domainParameterXref,
                paramBindings,
                session.getLoadQueryInfluencers(),
                factory.getSqlTranslationEngine()
            )
            .translate();

        // Step 2: Build JDBC parameter bindings (supports parameterized queries)
        JdbcParameterBindings jdbcParameterBindings = buildJdbcParameterBindings(
            execCtx, domainParameterXref, sqmInterpretation);

        // Step 3: Translate SQL AST to JDBC operation (produces the SQL string)
        SqlAstTranslator<? extends JdbcOperationQueryMutation> translator = factory.getJdbcServices()
            .getJdbcEnvironment()
            .getSqlAstTranslatorFactory()
            .buildMutationTranslator(factory, sqmInterpretation.getSqlAst());

        JdbcOperationQueryMutation jdbcMutation = translator.translate(jdbcParameterBindings, queryOptions);
        return jdbcMutation.getSqlString();
    }

    private static JdbcParameterBindings buildJdbcParameterBindings(
            DomainQueryExecutionContext execCtx,
            DomainParameterXref domainParameterXref,
            SqmTranslation<?> sqmInterpretation) {

        Map<QueryParameterImplementor<?>,
            Map<SqmParameter<?>, List<JdbcParametersList>>> jdbcParamsXref =
            SqmUtil.generateJdbcParamsXref(domainParameterXref, sqmInterpretation::getJdbcParamsBySqmParam);

        Map<SqmParameter<?>, MappingModelExpressible<?>> sqmParamMappingTypeResolutions =
            sqmInterpretation.getSqmParameterMappingModelTypeResolutions();

        return SqmUtil.createJdbcParameterBindings(
            execCtx.getQueryParameterBindings(),
            domainParameterXref,
            jdbcParamsXref,
            new SqmParameterMappingModelResolutionAccess() {
                @Override
                public <T> MappingModelExpressible<T> getResolvedMappingModelType(SqmParameter<T> parameter) {
                    return (MappingModelExpressible<T>) sqmParamMappingTypeResolutions.get(parameter);
                }
            },
            execCtx.getSession()
        );
    }
}
